#!/usr/bin/env ruby

# if this is the initial run, setup the load path and grab a mutex
if ! defined?(Sinatra)
  root_dir = File.dirname(__FILE__)
  $:.unshift "#{root_dir}/rack/lib" if File.directory?("#{root_dir}/rack")
  $:.unshift "#{root_dir}/sinatra/lib" if File.directory?("#{root_dir}/sinatra")
  $:.unshift "#{root_dir}/lib"
  $:.unshift "#{root_dir}"
end

require 'rubygems'
require 'wink'

Wink.run! 'wink.conf' unless Wink.reloading?


# Reloading =================================================================

if Wink.development? && Wink.reloading?

    # We also remove DataMapper's schema cache and subclass tracking since it keeps
    # references to the class objects we've removed above. This ensures that old
    # class objects can be GC'd.
    DataMapper::Database[:default].adapter.instance_variable_set(:@schema, nil)
    DataMapper::Persistence.subclasses.clear

    Wink.send :remove_const, 'VERSION'

    # reload all wink sources.
    load 'wink.rb'
    load 'wink.conf'
    Model.reload_all
    load 'wink/web.rb'

end
